name: rhasspy_mobile_app
description: A simple app to interact with rhasspy.

version: 1.7.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  shared_preferences: ^0.5.12+2
  permission_handler: ^5.0.1+1    
  flutter_audio_recorder: ^0.5.5
  path_provider:
  file_picker: ^2.0.13
  audioplayers: ^0.17.0
  dio: ^3.0.10
  flushbar: ^1.10.4
  mqtt_client: ^8.1.0
  provider: ^4.3.2+2
  flutter_local_notifications: ^3.0.1
  material_design_icons_flutter: ^4.0.5755
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  http_mock_adapter: ^0.1.3
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  image_path: 'assets/images/rhasspy.png'
  android: true
  ios: true
